Try multiple ssh commands

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -168,7 +168,7 @@ jobs:
         echo "${{ env.EC2_PRIV_KEY }}" > spaceaffairs-key.pem
         chmod 600 spaceaffairs-key.pem
 
-    - name: Deploy to EC2 and set Environment Variables
+    - name: Deploy to EC2
       env:
         EC2_HOST: ${{ needs.terraform.outputs.ec2host }}
       run: |
@@ -180,6 +180,13 @@ jobs:
       run: |
         ssh -o StrictHostKeyChecking=no -i spaceaffairs-key.pem "Administrator@${EC2_HOST}" powershell -Command "[Environment]::SetEnvironmentVariable('CLIENT_SECRET', '${{ env.GOOGLE_CLIENT_SECRET}}', 'Machine')"
 
+        ssh -o StrictHostKeyChecking=no -i spaceaffairs-key.pem "Administrator@${EC2_HOST}" powershell -Command "if (!(Test-Path 'C:\nssm\nssm.exe')) { Write-Error 'nssm not found at C:\nssm\nssm.exe'; exit 1 }"
+    
+        ssh -o StrictHostKeyChecking=no -i spaceaffairs-key.pem "Administrator@${EC2_HOST}" powershell -Command "if (Get-Service -Name 'SpaceAffairsAPI' -ErrorAction SilentlyContinue) { C:\nssm\nssm.exe stop SpaceAffairsAPI; C:\nssm\nssm.exe remove SpaceAffairsAPI confirm }"
+
+        ssh -o StrictHostKeyChecking=no -i spaceaffairs-key.pem "Administrator@${EC2_HOST}" powershell -Command "C:\nssm\nssm.exe install SpaceAffairsAPI 'C:\deploy\SpaceAffairsAPI.exe'"
+
+        ssh -o StrictHostKeyChecking=no -i spaceaffairs-key.pem "Administrator@${EC2_HOST}" powershell -Command "C:\nssm\nssm.exe start SpaceAffairsAPI"
   flyway:
     needs:
       - terraform
